# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Al Delmerico, PhD
tagline:          'Behavioral Health Geographer'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Al Delmerico'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
